---
- name: "Creating Network: {{ gce_network_name }}"
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - instance.config
  tasks:
    - name: "SUBNET: Creating: {{ gce_network_name }}"
      gce_net: name={{ gce_network_name }} state=present mode=custom
               subnet_name={{ gce_subnetwork_name }} subnet_region={{ gce_region }} ipv4_range={{ gce_ipv4_prefix }}
               credentials_file={{ gce_credentials_file }}
               project_id={{ gce_project_id }} service_account_email={{ gce_service_account_email }}
      tags: [ gce, network, subnet ]

    - name: "SECURITY GROUP: Creating Firewall Rules"
      gce_net: name={{ gce_network_name }} state=present
               fwname="{{ gce_network_name }}-{{ item.name }}"
               allowed={{ item.allow }}  src_range={{ item.range }}   target_tags={{ item.tag }}
               credentials_file={{ gce_credentials_file }}
               project_id={{ gce_project_id }} service_account_email={{ gce_service_account_email }}
      with_items: "{{ gce_security_group }}"
      tags: [ ocp, network, sg ]
