--- 
- name: "Provisioning: {{ instance_name }}"
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files: 
     - instance.config
  roles: 
     - { role: checking_parameters }
     - { role: delete }
     - { role: create }

- name: Setting Up
  hosts: instance_group
  gather_facts: False
  vars_files:
     - instance.config
  roles:
     - { role: redhat_subscription }
     - { role: host_preparation }
     - { role: install_ansible }
     - { role: install_maven }

- name: Ready to go
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - instance.config
  roles:
     - { role: notification_slack }
  tasks:
     - debug: "msg='instance_name: ssh {{ ssh_username }}@{{ instance_public_ip }}'"
