--- 
- name: "Creating an instance: {{ instance_name }}"
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files: 
     - instance.config
  roles: 
     - { role: create }
  tasks:
     - debug: "msg='instance_name: ssh root@{{ instance_creation.instance_data[0].public_ip }}'"
