---
- name: "Deleting Network: {{ gce_network_name }}"
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - instance.config
  tasks:
    - name: "SECURITY GROUP: Deleting all Firewall Rules"
      gce_net: name={{ gce_network_name }} state=absent fwname={{ item.name }}
               subnet_name={{ gce_subnetwork_name }} subnet_region={{ gce_region }}
               credentials_file={{ gce_credentials_file }}
               project_id={{ gce_project_id }} service_account_email={{ gce_service_account_email }}
      with_items: "{{ gce_network_firewall_rules }}"

    - name: "SUBNET: Deleting"
      gce_net: name={{ gce_network_name }} state=absent
               mode=custom
               subnet_name={{ gce_subnetwork_name }} subnet_region={{ gce_region }}
               credentials_file={{ gce_credentials_file }}
               project_id={{ gce_project_id }} service_account_email={{ gce_service_account_email }}

    - name: "NETWORK: Deleting"
      gce_net: name={{ gce_network_name }} state=absent
               credentials_file={{ gce_credentials_file }}
               project_id={{ gce_project_id }} service_account_email={{ gce_service_account_email }}
