subscription_name: "Employee SKU"
subscription_type: "Virtual"
repositories:
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
    - rhel-7-server-ose-3.11-rpms
    - rhel-7-server-ansible-2.6-rpms
